footballfantasy/footballfantasy/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("ve_confirmation/<uidb64>/<token>", views.ve_confirmation, name="ve_confirmation"),
    path("verificationemail", views.verification_email, name="verificationemail"),
    path("forgot_password", views.forgot_password, name="forgot_password"),
    path("fp_confirmation", views.fp_confirmation, name='fp_confirmation'),
    path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password"),
    path("rp_confirmation", views.rp_confirmation, name="rp_confirmation"),
]

footballfantasy/footballfantasy/footballfantasy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name='footballfantasy'

urlpatterns = [
    path('', include('onboard.urls', namespace='onboard')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('createteam/', include('createteam.urls', namespace='createteam')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

footballfantasy/footballfantasy/home/urls.py
# onboard urls
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("<int:league_id>", views.home, name="home"),
]

footballfantasy/footballfantasy/onboard/urls.py
# onboard urls
from django.urls import path
from . import views

app_name = 'onboard'
urlpatterns = [
    path("", views.onboard, name="onboard"),
]

footballfantasy/footballfantasy/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from createteam.models import Team, League


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11, blank=False, null=False)
    is_email_verified = models.BooleanField(default=False)
    is_team_created = models.BooleanField(default=False)

    def __str__(self):
        return "%s | %s | %s | %s" % (self.user.id, self.user.email, self.phone_number, str(self.is_email_verified))


class User_Team(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    players = models.JSONField(null=True)
    team_format = models.JSONField(null=True)
    main_players = models.JSONField(null=True)
    user_score = models.FloatField(default=0)
    is_changed = models.BooleanField(default=False)
    
    def __str__(self):
        return self.user.email

footballfantasy/footballfantasy/accounts/views.py
import re
import json
import requests

from django.contrib import auth
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.template.response import TemplateResponse
from django.utils.encoding import force_bytes, force_text
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from home.models import Log
from .models import UserProfile

def log(title, message, data, is_what):
    if is_what == "is_info":
        log = Log.objects.create(title=title, message=message, data=data, is_info=True)
    elif is_what == "is_warning":
        log = Log.objects.create(title=title, message=message, data=data, is_warning=True)
    elif is_what == "is_error":
        log = Log.objects.create(title=title, message=message, data=data, is_error=True)
    log.save()


# func to send email for verification and reset password
def send_email(to, email_subject, email_body, called_func, request):
    try:
        email = EmailMessage(
            email_subject,
            email_body,
            settings.EMAIL_HOST_USER,
            to
        )
        email.send(fail_silently=False)
        data = json.dumps({"user":request.user.id, "where":{"app": "accounts", "view":called_func, "part":"send_email"}, "exception_message":"no exp"})
        log("success", "email send successfully", data, "is_info")
        return True
    except Exception as e:
        data = json.dumps({"user":request.user.id, "where":{"app": "accounts", "view":called_func, "part":"send_email"}, "exception_message":str(e)})
        log("exeption", "erorr while sending email", data,"is_error")
        return False


def signup(request):
    if request.user.is_authenticated:
        return redirect('onboard:onboard')
    email_regex = '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$'
    phone_regex = '(\+?98|0)9\d{7}'
    errors = {
        'first_name': [],
        'last_name': [],
        'email': [],
        'phone_number': [],
        'password1': [],
        'password2': []
    }

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['email']
        phone_number = request.POST['phone_number']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        # form validation

        # 1. check first_name and last_name are more than 3 chars
        if len(first_name) < 3:
            errors['first_name'].append('نام باید بیشتر از 3 کاراکتر باشد.')

        if len(last_name) < 3:
            errors['last_name'] = [
                'نام خانوادگی باید بیشتر از 3 کاراکتر باشد.']

        # 2. check email is not empty and is valid form
        if email:
            if not re.match(email_regex, email):
                errors['email'] = ['آدرس ایمیل معتبر نمی‌باشد.']

            if User.objects.filter(email=email).exists():
                errors['email'] = ['این ایمیل قبلا ثبت نام کرده است.']
        else:
            errors['email'] = ['فیلد ایمیل خالی است.']

        # 3. check phone number validation
        if not re.match(phone_regex, phone_number):
            errors['phone_number'] = [
                'شماره موبایل معتبر نمی‌باشد، باید به صورت ۰۹۱۲۱۲۳۴۵۶۷ وارد کنید.']

        # 4. check password1 and password2 are not empty and be equal and more than 8 char
        if len(password1) < 8:
            errors['password1'] = ['رمز عبور باید حداقل 8 حرف یا عدد باشد.']

        if not password2:
            errors['password2'] = ['رمز عبور باید حداقل 8 حرف یا عدد باشد.']

        if password1 != password2:
            errors['password2'] = ['تکرار رمز با خود رمز عبور برابر نیست.']
        
        # check if there is an error just send error and do notting else push data in user table
        if sum([len(errors[key]) for key in errors]):
            data = {
                'errors': errors,
                'user_data': {
                    'first_name': first_name,
                    'last_name': last_name,
                    'email': email,
                    'phone_number': phone_number,
                    'password1': '',
                    'password2': ''
                }
            }
            return TemplateResponse(request, 'accounts/signup.html', {'response': data})
        else:
            # if everything is ok create user and route to email verification page
            # user = User.objects.create_user(username='sia@hsn.com', password='123456789', email='sia@hsn.com', first_name='sia', last_name='hsn')
            # userprofile = UserProfile.objects.create(user, phone_number='09120535348')
            
            # check recapcha
            captcha_token=request.POST.get("g-recaptcha-response")
            cap_url="https://www.google.com/recaptcha/api/siteverify"
            cap_secret="6LcvJxYcAAAAADcCIaIUC16Qg-RvOWETI_iF6ydp"
            cap_data={"secret":cap_secret,"response":captcha_token}
            cap_server_response=requests.post(url=cap_url,data=cap_data)
            cap_json=json.loads(cap_server_response.text)

            if cap_json['success']==False:
                messages.error(request,"ریکپچا نامعتبر است. لطفا دوباره امتحان کنید.")
                return redirect("accounts:signup")
            try:
                user = User.objects.create_user(
                    username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                user.save()
                userprofile = UserProfile.objects.create(
                    user=user, phone_number=phone_number)
                userprofile.save()
                print('user created')
                auth.login(request, user)
                data = json.dumps({"user":request.user.id, "where":{"app": "accounts", "view":"sign_up", "part":"post->create user"}, "exception_message":"no exp"})
                log("signed-up", "user successfully signed up", data, "is_info")
                return redirect('accounts:verificationemail')
            except Exception as e:
                data = json.dumps({"user":email, "where":{"app": "accounts", "view":"sign_up", "part":"post->create user"}, "exception_message":str(e)})
                log("exeption", "erorr while create user", data,"is_error")
                return redirect('accounts:signup')
 
    else:
        return render(request, 'accounts/signup.html')


def login(request):
    if request.user.is_authenticated:
        return redirect('onboard:onboard')
    email_regex = '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$'
    errors = {
        'email': [],
        'password1': [],
    }

    if request.method == 'POST':
        email = request.POST['email']
        password1 = request.POST['password1']

        # 1. check email is not empty and is valid form
        if email:
            if not re.match(email_regex, email):
                errors['email'] = ['آدرس ایمیل معتبر نمی‌باشد.']

            if not User.objects.filter(email=email).exists():
                errors['email'] = ['این ایمیل در سامانه موجود نمی باشد']
            else:
                user_auth = auth.authenticate(request, username=email, password=password1)
        else:
            errors['email'] = ['فیلد ایمیل خالی است.']

        # 2. check password1 are not empty and be equal and more than 8 char
        if len(password1) < 8:
            errors['password1'] = ['رمز عبور باید حداقل 8 حرف یا عدد باشد.']

        if User.objects.filter(email=email).exists():
            if user_auth is None:
                errors['password1'] = ['رمز اشتباه است.']
            else:
                userprofile = UserProfile.objects.get(user=user_auth)

        # check recapcha
        captcha_token=request.POST.get("g-recaptcha-response")
        cap_url="https://www.google.com/recaptcha/api/siteverify"
        cap_secret="6LcvJxYcAAAAADcCIaIUC16Qg-RvOWETI_iF6ydp"
        cap_data={"secret":cap_secret,"response":captcha_token}
        cap_server_response=requests.post(url=cap_url,data=cap_data)
        cap_json=json.loads(cap_server_response.text)
        
        # check if there is an error just send error and do notting else push data in user table
        if sum([len(errors[key]) for key in errors]):
            data = {
                'errors': errors,
                'user_data': {
                    'email': email,
                    'password1': '',
                }
            }
            return TemplateResponse(request, 'accounts/login.html', {'response': data})
        elif cap_json['success']==False:
            messages.error(request,"ریکپچا نامعتبر است. لطفا دوباره امتحان کنید.")
            return redirect("accounts:login")
        elif not userprofile.is_email_verified:
            # if user not verified his email redirect user to verifiactionemail page
            auth.login(request, user_auth)
            return redirect('accounts:verificationemail')
        else:
            auth.login(request, user_auth)
            return redirect('createteam:chooseleague', hello='0')
    else:
        # auth.logout(request)
        return render(request, 'accounts/login.html')


def verification_email(request):
    # check if user not verified route to verificationemail page
    user_is_verified = UserProfile.objects.get(user_id=request.user.id)
    user_is_verified = user_is_verified.is_email_verified
    if user_is_verified:

footballfantasy/footballfantasy/templates/accounts/forgotpassword.html
{% extends "./template.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pt-sm-2 pt-md-4 pb-5">
        <div class="shadow-lg col col-md-8 col-lg-5 bg-body rounded p-4 p-md-5">
            <div class="text-center">
                <h3><i class="bi bi-file-lock2 text-info" style="font-size: 7rem;"></i></h3>
                <h2 class="text-center">فراموشی رمز عبور؟</h2>
                <p>شما می‌توانید رمز خود را اینجا بازیابی کنید. </p>
            </div>
            <form name="forgotpassword_form" action="forgot_password" method="POST" @submit.stop.prevent="submit" novalidate>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label">ایمیل</label>
                    <input name="email" type="email" class="form-control" id="email" placeholder="ایمیل خود را وارد کنید."  v-model="user.email" :class="validate_error('email')" required>
                    <div class="invalid-feedback" v-show="errors.email && errors.email.length">
                        <ol>
                            <li v-for="text in errors.email">[[ text ]]</li>
                        </ol>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block my-4">
                    <i class="bi bi-envelope"></i>
                     ارسال لینک بازیابی 
                </button>
            </form>
             <hr />
             <div class="clearfix">
                 <span class="float-start">
                     <a href="{% url 'onboard:onboard' %}" class="float-left">صفحه اصلی</a>
                 </span>
                 <span class="float-end">
                    <a href="{% url 'accounts:login' %}" >ورود</a>
                 </span>
             </div>
         </div>
    </div>
</div>
<div>
    {% for message in messages %}
        <h3> {{message}} </h3>
    {% endfor %}
</div>
{% endblock %}


{% block js %}
<script type = "text/javascript">
    {% if response %}
    var response = {{ response | safe }}
    {% else %}
    var response = { user_data: null, errors: null }
    {% endif %}
    app = new Vue({
        el: "#app",
        mounted() {
            this.$nextTick(function () {
                if(response.errors) {
                    for(var error in response.errors) {
                        if(response.errors[error] && response.errors[error].length)
                            this.validated = true
                    }
                }
            })
        },
        methods: {
            validate_error: function(name) {
                var has_error = this.errors[name] && this.errors[name].length
                return {
                    'is-invalid' : this.validated && has_error,
                    'is-valid' : this.validated && !has_error
                }
            },
            submit: function(e) {
                this.errors.email = []

                if(!this.user.email) {
                    this.errors.email.push("فیلد ایمیل خالی است.")
                }
                if(!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/.test(this.user.email)) {
                    this.errors.email.push("آدرس ایمیل معتبر نمی‌باشد.")
                }
               
                this.validated = true
                for(var error in this.errors) {
                    if(this.errors[error] && this.errors[error].length)
                        return
                }
                e.target.submit();
            }
        },
        data: {
            validated: false,
            user: response.user_data || {
                email : "",
            },
            errors: response.errors || {
                email: [],
            }
        }
    });
</script>
{% endblock %}

footballfantasy/footballfantasy/templates/accounts/fp-confirmation.html
{% extends "./template.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pt-sm-2 pt-md-4 pb-5">
        <div class="shadow-lg col col-md-8 col-lg-5 bg-body rounded p-4 p-md-5">
            <div class="text-center">
                <i class="bi bi-check-lg text-info" style="font-size: 7rem;"></i> 
                <h2>
                    <p>ایمیل ارسال شد</p>
                </h2>
                <hr />
                <p>{{user_name}}</p>
                <p>ایمیل بازیابی رمز عبور با موفقیت ارسال شد.</p>
                <p>لطفا برای تغییر رمز عبور به حساب ایمیل خود مراجعه کنید.</p>
                <a href="{% url 'accounts:login' %}" class="btn btn-primary mb-3">انتقال به صفحه ورود</a>
            </div>
        </div>
    </div>
</div>
<div>
    {% for message in messages %}
        <h3> {{message}} </h3>
    {% endfor %}
</div>
{% endblock %}


{% block js %}
<script type = "text/javascript">
</script>
{% endblock %}

footballfantasy/footballfantasy/templates/accounts/login.html
{% extends "./template.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pt-sm-2 pt-md-4 pb-5">
        <div class="shadow-lg col col-md-8 col-lg-5 bg-body rounded p-4 p-md-5">
            <form name="login_form" action="login" method="POST" @submit.stop.prevent="submit" novalidate>
                {% csrf_token %}
                <div class="text-center">
                    <i class="bi bi-person-circle text-info" style="font-size: 7rem;"></i>
                    <p class="h1 mb-5">
                        ورود
                    </p>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">ایمیل</label>
                    <input name="email" type="email" class="form-control" id="email"
                        placeholder="ایمیل خود را وارد کنید." v-model="user.email" :class="validate_error('email')"
                        required>
                    <div class="invalid-feedback" v-show="errors.email && errors.email.length">
                        <ol>
                            <li v-for="text in errors.email">[[ text ]]</li>
                        </ol>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="password1" class="form-label">رمز عبور</label>
                    <input name="password1" type="password" class="form-control" id="password1"
                        placeholder="رمز عبور خود را کنید." :class="validate_error('password1')"
                        v-model="user.password1" required>
                    <div class="invalid-feedback" v-show="errors.password1 && errors.password1.length">
                        <ol>
                            <li v-for="text in errors.password1">[[ text ]]</li>
                        </ol>
                    </div>
                    <a class="link-secondary" href="{% url 'accounts:forgot_password' %}">رمز عبور خود را فراموشی
                        کرده‌ام؟</a>
                </div>
                <div class="mb-3">
                    <div class="g-recaptcha" data-sitekey="6LcvJxYcAAAAANUG3SKJDxRURpoXBtqMRcqJ6hfW"></div>
                </div>
                <button type="submit" class="btn btn-primary btn-block my-4">
                    <i class="bi bi-person-check-fill"></i>
                    ورود
                </button>
            </form>

            {% for message in messages %}
                <div class="alert alert-danger p-2" role="alert">
                    <span>
                        {{ message }}
                    </span>
                </div>
            {% endfor %}

            <hr />
            <div class="clearfix">
                <span class="float-start">
                    <a href="{% url 'onboard:onboard' %}" class="float-left link-primary">صفحه اصلی</a>
                </span>
                <span class="float-end">
                    <a class="link-primary" href="{% url 'accounts:signup' %}">ثبت نام</a>
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script type="text/javascript">
    {% if response %}
    var response = {{ response | safe }}
    {% else %}
    var response = { user_data: null, errors: null }
    {% endif %}
    app = new Vue({
        el: "#app",
        mounted() {
            this.$nextTick(function () {
                if (response.errors) {
                    for (var error in response.errors) {
                        if (response.errors[error] && response.errors[error].length)
                            this.validated = true
                    }
                }
            })
        },
        methods: {
            validate_error: function (name) {
                var has_error = this.errors[name] && this.errors[name].length
                return {
                    'is-invalid': this.validated && has_error,
                    'is-valid': this.validated && !has_error
                }
            },
            submit: function (e) {
                this.errors.email = []
                this.errors.password1 = []

                if (!this.user.email) {
                    this.errors.email.push("فیلد ایمیل خالی است.")
                }
                if (!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/.test(this.user.email)) {
                    this.errors.email.push("آدرس ایمیل معتبر نمی‌باشد.")
                }
                if (!this.user.password1) {
                    this.errors.password1.push("فیلد رمز عبور خالی است!")
                }
                if (this.user.password1.length < 8) {
                    this.errors.password1.push("رمز عبور باید حداقل 8 حرف یا عدد باشد.")
                }
                this.validated = true
                for (var error in this.errors) {
                    if (this.errors[error] && this.errors[error].length)
                        return
                }
                e.target.submit();
            }
        },
        data: {
            validated: false,
            user: response.user_data || {
                email: "",
                password1: "",
            },
            errors: response.errors || {
                email: [],
                password1: [],
            }
        }
    });
</script>
{% endblock %}

footballfantasy/footballfantasy/templates/accounts/resetpassword.html
{% extends "./template.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pt-sm-2 pt-md-4 pb-5">
        <div class="shadow-lg col col-md-8 col-lg-5 bg-body rounded p-4 p-md-5">
             <form name="reset_password_form" action="reset_password" method="post" @submit.stop.prevent="submit" novalidate>
                {% csrf_token %}
                <div class="text-center">
                    <i class="bi bi-file-lock text-info" style="font-size: 7rem;"></i>
                    <p class="h2 mb-4 text-center">
                        بازیابی رمز عبور
                    </p>
                </div>
                <div class="mb-3">
                    <label for="password1" class="form-label">رمز عبور جدید</label>
                    <input name="password1" type="password" class="form-control" id="password1" placeholder="رمز عبور جدید خود را با حداقل ۸ کارکتر وارد کنید." :class="validate_error('password1')" v-model="user.password1" required>
                    <div class="invalid-feedback" v-show="errors.password1 && errors.password1.length">
                        <ol>
                            <li v-for="text in errors.password1">[[ text ]]</li>
                        </ol>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="password2" class="form-label">تکرار رمز عبور جدید</label>
                    <input name="password2" type="password" class="form-control" id="password2" placeholder="رمز عبور جدید خود را دوباره وارد کنید." :class="validate_error('password2')" v-model="user.password2" required>
                    <div class="invalid-feedback" v-show="errors.password2 && errors.password2.length">
                        <ol>
                            <li v-for="text in errors.password2">[[ text ]]</li>
                        </ol>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block my-4">
                    <i class="bi bi-lock-fill"></i>
                    بازیابی رمز عبور
                </button>
            </form>
             <hr />
             <div class="clearfix">
                 <span class="float-start">
                     <a href="{% url 'onboard:onboard' %}" class="float-left">صفحه اصلی</a>
                 </span>
                 <span class="float-end">
                    <a href="{% url 'accounts:login' %}" >ورود</a>
                 </span>
             </div>
         </div>
    </div>
</div>
<div>
    {% for message in messages %}
        <h3> {{message}} </h3>
    {% endfor %}
</div>
{% endblock %}


{% block js %}
<script type = "text/javascript">
    {% if response %}
    var response = {{ response | safe }}
    {% else %}
    var response = { user_data: null, errors: null }
    {% endif %}
    app = new Vue({
        el: "#app",
        mounted() {
            this.$nextTick(function () {
                if(response.errors) {
                    for(var error in response.errors) {
                        if(response.errors[error] && response.errors[error].length)
                            this.validated = true
                    }
                }
            })
        },
        methods: {
            validate_error: function(name) {
                var has_error = this.errors[name] && this.errors[name].length
                return {
                    'is-invalid' : this.validated && has_error,
                    'is-valid' : this.validated && !has_error
                }
            },
            submit: function(e) {
                this.errors.password1 = []
                this.errors.password2 = []

                if(!this.user.password1) {
                    this.errors.password1.push("فیلد رمز عبور خالی است!")
                }
                if (this.user.password1.length < 8) {
                    this.errors.password1.push("رمز عبور باید حداقل 8 حرف یا عدد باشد.")
                }

                if (this.user.password2 != this.user.password1) {
                    this.errors.password2.push("تکرار رمز با خود رمز عبور برابر نیست.")
                }
                this.validated = true
                for(var error in this.errors) {
                    if(this.errors[error] && this.errors[error].length)
                        return
                }
                e.target.submit();
            }
        },
        data: {
            validated: false,
            user: response.user_data || {

                password1 : "",
                password2 : "",
            },
            errors: response.errors || {
                password1: [],
                password2: [],
            }
        }
    });
</script>
{% endblock %}

footballfantasy/footballfantasy/templates/accounts/rp-confirmation.html
{% extends "./template.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pt-sm-2 pt-md-4 pb-5">
        <div class="shadow-lg col col-md-8 col-lg-5 bg-body rounded p-4 p-md-5">
            <div class="text-center">
                <i class="bi bi-check-lg text-info" style="font-size: 7rem;"></i>
                <h2>
                    <p>رمز تغییر کرد</p>
                </h2>
                <hr />
                <p class="pt-4 pb-4">رمز شما با موفقیت تغییر کرد. لطفا برای ادامه دوباره ورود شوید.</p>
                <a href="{% url 'accounts:login' %}" class="btn btn-primary mb-3">انتقال به صفحه ورود</a>
            </div>
        </div>
    </div>
</div>
<div>
    {% for message in messages %}
        <h3> {{message}} </h3>
    {% endfor %}
</div>
{% endblock %}


{% block js %}
<script type = "text/javascript">
</script>
{% endblock %}

footballfantasy/footballfantasy/templates/accounts/template.html
{% extends "../base.html" %}

footballfantasy/footballfantasy/templates/accounts/ve-confirmation.html
{% extends "./template.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pt-sm-2 pt-md-4 pb-5">
        <div class="shadow-lg col col-md-8 col-lg-5 bg-body rounded p-4 p-md-5">
            <div class="text-center">
                <i class="bi bi-check-square-fill text-info" style="font-size: 7rem;"></i> 
                <p>Email Verified</p>
                <hr />
                <p>{{user_name}}</p>
                <p>ایمیل شما با موفقیت تایید شد.</p>
                <p>لطفا برای ادامه دوباره وارد شوید.</p>
                <a href="{% url 'accounts:login' %}" class="btn btn-primary mb-3">انتقال به صفحه ورود</a>
            </div>
        </div>
    </div>
</div>
<div>
    {% for message in messages %}
        <h3> {{message}} </h3>
    {% endfor %}
</div>
{% endblock %}


{% block js %}
<script type = "text/javascript">
</script>
{% endblock %}