footballfantasy/footballfantasy/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("ve_confirmation/<uidb64>/<token>", views.ve_confirmation, name="ve_confirmation"),
    path("verificationemail", views.verification_email, name="verificationemail"),
    path("forgot_password", views.forgot_password, name="forgot_password"),
    path("fp_confirmation", views.fp_confirmation, name='fp_confirmation'),
    path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password"),
    path("rp_confirmation", views.rp_confirmation, name="rp_confirmation"),
]

footballfantasy/footballfantasy/createteam/urls.py
from django.urls import path
from . import views

app_name='createteam'

urlpatterns = [
    path("<task>/<league_id>/<hash>", views.create_team, name="createteam"),
    path("chooseleague/<hello>", views.choose_league, name="chooseleague"),
]

footballfantasy/footballfantasy/footballfantasy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name='footballfantasy'

urlpatterns = [
    path('', include('onboard.urls', namespace='onboard')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('createteam/', include('createteam.urls', namespace='createteam')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

footballfantasy/footballfantasy/home/urls.py
# onboard urls
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("<int:league_id>", views.home, name="home"),
]

footballfantasy/footballfantasy/onboard/urls.py
# onboard urls
from django.urls import path
from . import views

app_name = 'onboard'
urlpatterns = [
    path("", views.onboard, name="onboard"),
]

footballfantasy/footballfantasy/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css">
  <!-- <link href="{% static 'onboard/css/styles.css' %}" rel="stylesheet" /> -->
  <link href="{% static 'base/css/styles.css' %}" rel="stylesheet" />
  <link rel="shortcut icon" type="image/png" href="{% static 'base/images/favicon.png' %}" />
  {% block css %}
  {% endblock %}
  {% block meta %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>

<body class="body">
  <div id="app">
    {% block menu %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100">
      <div class="container">
        <a href="{% url 'onboard:onboard' %}">
          <img class="img-fluid" style="height: 3.2rem;" src="{% static 'logos/fflogo.png' %}" alt="logo" />
          <!-- <img class="d-xs-block d-sm-block d-md-block d-lg-none img-fluid" style="height: 6vw;" src="{% static 'logos/fflogo.png' %}" alt="logo" /> -->
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07"
          aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" style="color: white;">
                {{ user.first_name }} {{ user.last_name }}
              </a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" style="color: white;" href="{% url 'admin:index' %}">پنل مدیریت</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link " style="color: white;" href="{% url 'createteam:chooseleague' hello='0' %}">تیم من</a>
            </li>
            <li class="nav-item"><a class="nav-link ps-0" style="color: white;"
                href="{% url 'accounts:logout' %}">خروج</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" style="color: white;"
                href="{% url 'accounts:signup' %}">ثبت‌نام</a></li>
            <li class="nav-item"><a class="nav-link" style="color: white;" href="{% url 'accounts:login' %}">ورود</a>
            </li>
            {% endif %}
          </ul>

        </div>
      </div>
    </nav>
    {% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}
    {% endblock %}
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
  integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
  integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript">
  Vue.options.delimiters = ["[[", "]]"]
</script>
{% block js %}
{% endblock %}

</html>